name: CI - Build & Push Images

on:
  push:
    branches: [ main ]
    paths:
      - 'user-service/**'
      - 'order-service/**'
      - 'api-gateway/**'
      - '.github/workflows/ci.yaml'
  workflow_dispatch:

env:
  REGISTRY: mydevopsdemo01.azurecr.io
  IMAGE_TAG: v1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & push user-service
        run: |
          cd user-service
          docker build -t $REGISTRY/user-service:${IMAGE_TAG} .
          docker push $REGISTRY/user-service:${IMAGE_TAG}

      - name: Build & push order-service
        run: |
          cd $GITHUB_WORKSPACE/order-service
          docker build -t $REGISTRY/order-service:${IMAGE_TAG} .
          docker push $REGISTRY/order-service:${IMAGE_TAG}

      - name: Build & push api-gateway
        run: |
          cd $GITHUB_WORKSPACE/api-gateway
          docker build -t $REGISTRY/api-gateway:${IMAGE_TAG} .
          docker push $REGISTRY/api-gateway:${IMAGE_TAG}
